# Generated by Django 6.1 on 2026-08-16 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_seat_reserved_at_seat_reserved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('razorpay_order_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=12)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='How many prior payment attempts preceded this one for the same seats.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seats', models.ManyToManyField(related_name='payments', to='movies.seat')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='movies.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
