# Generated by Django 6.1.1 on 2026-09-06 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_refunded_amount_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('pdf_file', models.FileField(upload_to='tickets/%Y/%m/')),
                ('qr_verification_url', models.URLField(blank=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed (retries exhausted)')], default='pending', max_length=10)),
                ('email_attempts', models.PositiveIntegerField(default=0)),
                ('last_email_error', models.CharField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='payments.payment')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
