# Generated by Django 6.1.1 on 2026-09-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_dashboard', 'Can view analytics dashboard'), ('export_dashboard_reports', 'Can export analytics dashboard reports as CSV')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
