# Generated by Django 6.1 on 2026-08-16 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_seat_reserved_at_seat_reserved_by'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='The verified payment that confirmed this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='payments.payment'),
        ),
    ]
