# Generated by Django 6.1.1 on 2026-09-06 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_booking_movies_book_booked__a7ab7e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Base ticket price in INR - used for price sorting/filtering in movie discovery.', max_digits=8),
        ),
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text='City this theater/screen is in - used for movie discovery filtering.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['city', 'time'], name='movies_thea_city_3d4d26_idx'),
        ),
        migrations.AddField(
            model_name='recentlyviewed',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='recentlyviewed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recentlyviewed',
            index=models.Index(fields=['user', '-viewed_at'], name='movies_rece_user_id_49af0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewed',
            unique_together={('user', 'movie')},
        ),
    ]
